
services:
  agent:
    container_name: agent
    image: grafana/agent
    volumes:
      - ./agent:/etc/agent
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
     - /bin/agent
     - -config.file=/etc/agent/agent-config.yml
    ports:
      - "2004:12345"
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.3.2
    volumes:
      - ./grafana:/var/lib/grafana
    ports: 
      - "2000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    networks:
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki:/etc/loki
    ports: 
      - "2001:3100"
    networks:
      - monitoring

  mimir:
    container_name: mimir
    image: grafana/mimir:2.6.0
    command: -config.file=/etc/mimir/mimir-config.yml
    volumes:
      - ./mimir:/etc/mimir
    ports: 
      - "2002:9009"
    networks:
      - monitoring

  tempo:
    container_name: tempo
    image: grafana/tempo
    command: -config.file=/etc/tempo/tempo-config.yml
    volumes:
      - ./tempo:/etc/tempo
    ports: 
      - "2003:3200"   # tempo
      - "14268"  # jaeger ingest
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    networks:
      - monitoring

networks:
  monitoring:
      name: network_monitoring